CREATE PROCEDURE SP_BUSCA
@ID VARCHAR(2)
AS
SELECT * FROM [dbo].[ciudad] WHERE [idciu]=@ID
GO

EXEC SP_BUSCA 'LI'
GO

CREATE PROCEDURE SP_LISTACIUDAD
AS
SELECT * FROM [dbo].[ciudad]
GO

EXEC SP_LISTACIUDAD 
GO

CREATE PROCEDURE SP_INSERTAR_CIUDAD
@idCiu VARCHAR(2),
@desCiu VARCHAR(30),
@idPais VARCHAR(2)
AS
INSERT INTO [dbo].[ciudad] VALUES(@idCiu, @desCiu, @idPais)
GO

EXEC SP_INSERTAR_CIUDAD 'TE', 'JFDJFD', 'PE'
GO

CREATE PROCEDURE SP_EDITAR_CIUDAD
@idCiu VARCHAR(2),
@desCiu VARCHAR(30),
@idPais VARCHAR(2)
AS
UPDATE [dbo].[ciudad] 
SET [desciu]=@desCiu,[idpais]=@idPais WHERE [idciu]=@idCiu
GO

EXEC SP_EDITAR_CIUDAD 'TE', 'XXXXXXXX12', 'PE'
GO

CREATE PROCEDURE SP_ELIMINAR_CIUDAD
@idCiu VARCHAR(2)
AS
DELETE FROM [dbo].[ciudad] WHERE [idciu]=@idCiu
GO

EXEC SP_ELIMINAR_CIUDAD 'TE'
GO

CREATE PROCEDURE SP_LISTA_PAIS
AS
SELECT * FROM [dbo].[pais]
GO

EXEC SP_LISTA_PAIS 
GO